sudo: false
language: php
php:
  - 5.5

before_script:
  - git clone --branch 8.4.x https://git.drupal.org/project/drupal.git
  - cd drupal
  # Perform a Composer install. Composer update --prefer-lowest doesn't merge
  # properly with wikimedia/composer-merge-plugin unless there is already a
  # vendor/.
  - composer install --no-progress --prefer-dist

script:
  - wget https://www.drupal.org/files/issues/2887000_57.patch
  - git apply 2887000_57.patch
  # Update with --prefer-lowest.
  - composer update --prefer-lowest --no-progress --prefer-dist
  # Run only unit tests because they have no dependencies to set up.
  - ./vendor/bin/phpunit -c core/ --testsuite unit
  # Update.
  - composer update --no-progress --prefer-dist
  # Re-run the tests.
  - ./vendor/bin/phpunit -c core/ --testsuite unit
